version: '3'
services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: zorovhs
      MONGO_INITDB_ROOT_PASSWORD: anhtuvhs
    ports:
      - 27018:27017
    volumes:
      - ./docker_data:/data/db
    networks:
      - demo-network
networks:
  demo-network:
    driver: bridge